### ISSUE TITLE
tarteaucitron.js:212 Uncaught TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by basemedia** [GuillaumeKadolis/k_cookies#1]
Hello,

I installed the module on Prestahop 1.6.5 all is well. But when I activate i am getting the following message in console log;

tarteaucitron.js:212 Uncaught TypeError: Cannot read property 'title' of undefined
at tarteaucitron.js:212
at Array.sort (/native)
at tarteaucitron.js:211
at HTMLScriptElement.script.onreadystatechange.script.onload [as onreadystatechange] (tarteaucitron.js:1123)
(anonymous) @ tarteaucitron.js:212
(anonymous) @ tarteaucitron.js:211
script.onreadystatechange.script.onload @ tarteaucitron.js:1123
load (async)
addScript @ tarteaucitron.js:1119
load @ tarteaucitron.js:201
(anonymous) @ tarteaucitron.js:36
load (async)
init @ tarteaucitron.js:35
(anonymous) @ (index):171

Working on a nl (netherlands) language.

Thanks. Luke

**Comment by duGuillaume** [comment]
This error should be fixed try to dl again k_cookies.script.tpl into templates/hook/
