### ISSUE TITLE
tarteaucitron.js#L201 Error loading tarteaucitron.services.js file with cache and JS concatenation enabled

### ISSUE THREAD

**Issue by thibault78580** [GuillaumeKadolis/k_cookies#2]
https://github.com/GuillaumeKadolis/k_cookies/blob/31bbfe9bd28f5272dba314bf99b70cea89b00eb6/views/js/tarteaucitron.js#L201 

When activating the cache and concatenation of js files, there is an error loading the tarteaucitron.services.js file because the script takes the URL of the files (url of the cached files) include line 8. Do you have an idea to resolve this problem?

Best regards.

**Comment by thebat98** [comment]
Hi,
Same problem for me, I had to edit /k_cookies/views/js/tarteaucitron.js to change two lines at the top :

`path = 'https://www.yourwebsite.com/modules/k_cookies/views/js/tarteaucitron.js',`
`cdn = 'https://www.yourwebsite.com/modules/k_cookies/views/js/',`

This is not the right solution but it's working.

**Comment by duGuillaume** [comment]
hi, 
I push 1.1.1version (v1.7 for now) which added new services and fixed this issue, 
could you tell me if this solve your pb ?

**Comment by thebat98** [comment]
Hi,
Thanks for the update. I can't check because I'm only using 1.6 version (for now !).
Regards

**Comment by duGuillaume** [comment]
@thebat98 
here a none tested 1.6 version
[k_cookies.zip](https://github.com/GuillaumeKadolis/k_cookies/files/2214081/k_cookies.zip)

**Comment by thebat98** [comment]
Hi,

Same problem for me with this version.
My guess is you should not use JS to create "path" and "cdn" variables. Otherwise you'll be facing too many issues with CCC or other cache systems (like additional plugins).
One other solution souhld be using PHP and variables directly written in *.tpl files but it's probably not a best practice...

Regards

**Comment by duGuillaume** [comment]
mhh ok, i'll do more test tonight i'll come back to you tomorrow

**Comment by duGuillaume** [comment]
@thebat98 - @thibault78580
I made somes tests and this work for me on 1.6 with JS smart cache and minified.
I'm sorry, i don't use CCC so i didn't tested it

[k_cookies.zip](https://github.com/GuillaumeKadolis/k_cookies/files/2222613/k_cookies.zip)
